---
- name: installing dotnet 7
  hosts: all
  become: yes
  tasks:
    - name: downloading the microsoft debian packages
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/22.10/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
    - name: installing debian package
      apt:
        deb: /tmp/packages-microsoft-prod.deb
    - name: installing donet 7
      apt:
        update_cache: true
        name: dotnet-sdk-7.0
        state: present







